apiVersion: v1
kind: Service
metadata:
  name: tinycache
  labels:
    app: tinycache
spec:
  clusterIP: None
  selector:
    app: tinycache
  ports:
    - name: client
      port: 11211
      targetPort: 11211
    - name: internal
      port: 11311
      targetPort: 11311
    - name: health
      port: 9090
      targetPort: 9090
